module(...)

--auto generate in editorgui.GenAudioData
DATA={
      --剑侠客  1=攻击  2=施法  3=挨打   4=防御  5=倒地
    jxk1=[[Audio/Sound/War/jxk1.ogg]],
	jxk2=[[Audio/Sound/Model/jxk2.mp3]],
	jxk3=[[Audio/Sound/Model/jxk3.mp3]],
    jxk4=[[Audio/Sound/Model/jxk4.mp3]],
	jxk5=[[Audio/Sound/Model/jxk5.mp3]],

	--龙太子
	ltz1=[[Audio/Sound/War/ltz1.ogg]],
	ltz2=[[Audio/Sound/Model/ltz2.mp3]],
	ltz3=[[Audio/Sound/Model/ltz3.mp3]],
	ltz4=[[Audio/Sound/Model/ltz4.mp3]],
	ltz5=[[Audio/Sound/Model/ltz5.mp3]],

	--飞燕女
	fyn1=[[Audio/Sound/War/fyn1.ogg]],
	fyn2=[[Audio/Sound/Model/fyn2.mp3]],
	fyn3=[[Audio/Sound/Model/fyn3.mp3]],
	fyn4=[[Audio/Sound/Model/fyn4.mp3]],
	fyn5=[[Audio/Sound/Model/fyn5.mp3]],
    --虎头怪
    htg1=[[Audio/Sound/War/htg1.ogg]],
    htg2=[[Audio/Sound/Model/htg2.mp3]],
	htg3=[[Audio/Sound/Model/htg3.mp3]],
	htg4=[[Audio/Sound/Model/htg4.mp3]],
	htg5=[[Audio/Sound/Model/htg5.mp3]],

	--舞天姬
	wtj1=[[Audio/Sound/War/wtj1.ogg]],
    wtj2=[[Audio/Sound/Model/wtj2.mp3]],
	wtj3=[[Audio/Sound/Model/wtj3.mp3]],
	wtj4=[[Audio/Sound/Model/wtj4.mp3]],
	wtj5=[[Audio/Sound/Model/wtj5.mp3]],

	--骨精灵
	gjl1=[[Audio/Sound/War/gjl1.ogg]],
    gjl2=[[Audio/Sound/Model/gjl2.mp3]],
	gjl3=[[Audio/Sound/Model/gjl3.mp3]],
	gjl4=[[Audio/Sound/Model/gjl4.mp3]],
	gjl5=[[Audio/Sound/Model/gjl5.mp3]],


	--大海龟
	dhg1=[[Audio/Sound/War/dhg1.ogg]],
	dhg2=[[Audio/Sound/Model/dhg2.mp3]],
	dhg3=[[Audio/Sound/Model/dhg3.mp3]],
	dhg4=[[Audio/Sound/Model/dhg4.mp3]],
	dhg5=[[Audio/Sound/Model/dhg5.mp3]],

	--马面
	mm1=[[Audio/Sound/War/mm1.ogg]],
	mm2=[[Audio/Sound/Model/mm2.mp3]],
	mm3=[[Audio/Sound/Model/mm3.mp3]],
	mm4=[[Audio/Sound/Model/mm4.mp3]],
	mm5=[[Audio/Sound/Model/mm5.mp3]],
	--狸
	l1=[[Audio/Sound/War/l1.ogg]],
	l2=[[Audio/Sound/Model/l2.mp3]],
	l3=[[Audio/Sound/Model/l3.mp3]],
	l4=[[Audio/Sound/Model/l4.mp3]],
	l5=[[Audio/Sound/Model/l5.mp3]],
	--牛头
	nt1=[[Audio/Sound/War/nt1.ogg]],
	nt2=[[Audio/Sound/Model/nt2.mp3]],
	nt3=[[Audio/Sound/Model/nt3.mp3]],
	nt4=[[Audio/Sound/Model/nt4.mp3]],
	nt5=[[Audio/Sound/Model/nt5.mp3]],
	--古代瑞兽
	gdrs1=[[Audio/Sound/War/gdrs1.ogg]],
	gdrs2=[[Audio/Sound/Model/gdrs2.mp3]],
	gdrs3=[[Audio/Sound/Model/gdrs3.mp3]],
	gdrs4=[[Audio/Sound/Model/gdrs4.mp3]],
	gdrs5=[[Audio/Sound/Model/gdrs5.mp3]],
	--凤凰
	fh1=[[Audio/Sound/War/fh1.ogg]],
	fh2=[[Audio/Sound/Model/fh2.mp3]],
	fh3=[[Audio/Sound/Model/fh3.mp3]],
	fh4=[[Audio/Sound/Model/fh4.mp3]],
	fh5=[[Audio/Sound/Model/fh5.mp3]],
	--天兵
	tb1=[[Audio/Sound/War/tb1.ogg]],
	tb2=[[Audio/Sound/Model/tb2.mp3]],
	tb3=[[Audio/Sound/Model/tb3.mp3]],
	tb4=[[Audio/Sound/Model/tb4.mp3]],
	tb5=[[Audio/Sound/Model/tb5.mp3]],
	--星灵仙子
	xlxz1=[[Audio/Sound/War/xlxz1.ogg]],
	xlxz2=[[Audio/Sound/Model/xlxz2.mp3]],
	xlxz3=[[Audio/Sound/Model/xlxz3.mp3]],
	xlxz4=[[Audio/Sound/Model/xlxz4.mp3]],
	xlxz5=[[Audio/Sound/Model/xlxz5.mp3]],
	--»ìãçÊÞ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hd1=[[Audio/Sound/War/hd1.ogg]],
	hd2=[[Audio/Sound/Model/hd2.mp3]],
	hd3=[[Audio/Sound/Model/hd3.mp3]],
	hd4=[[Audio/Sound/Model/hd4.mp3]],
	hd5=[[Audio/Sound/Model/hd5.mp3]],
	--³¤Ã¼Áéºï£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	cmlh1=[[Audio/Sound/War/cmlh1.ogg]],
	cmlh2=[[Audio/Sound/Model/cmlh2.mp3]],
	cmlh3=[[Audio/Sound/Model/cmlh3.mp3]],
	cmlh4=[[Audio/Sound/Model/cmlh4.mp3]],
	cmlh5=[[Audio/Sound/Model/cmlh5.mp3]],
	--º£ÐÇ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hx1=[[Audio/Sound/War/hx1.ogg]],
	hx2=[[Audio/Sound/Model/hx2.mp3]],
	hx3=[[Audio/Sound/Model/hx3.mp3]],
	hx4=[[Audio/Sound/Model/hx4.mp3]],
	hx5=[[Audio/Sound/Model/hx5.mp3]],
	--À×ÄñÈË£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ----------------
	lnr1=[[Audio/Sound/War/lnr1.ogg]],
	lnr2=[[Audio/Sound/Model/lnr2.mp3]],
	lnr3=[[Audio/Sound/Model/lnr3.mp3]],
	lnr4=[[Audio/Sound/Model/lnr4.mp3]],
	lnr5=[[Audio/Sound/Model/lnr5.mp3]],
	--Ò°¹í£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	yg1=[[Audio/Sound/War/yg1.ogg]],
	yg2=[[Audio/Sound/Model/yg2.mp3]],
	yg3=[[Audio/Sound/Model/yg3.mp3]],
	yg4=[[Audio/Sound/Model/yg4.mp3]],
	yg5=[[Audio/Sound/Model/yg5.mp3]],
	--ÂüÖéÉ³»ª£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	mzsh1=[[Audio/Sound/War/mzsh1.ogg]],
	mzsh2=[[Audio/Sound/Model/mzsh2.mp3]],
	mzsh3=[[Audio/Sound/Model/mzsh3.mp3]],
	mzsh4=[[Audio/Sound/Model/mzsh4.mp3]],
	mzsh5=[[Audio/Sound/Model/mzsh5.mp3]],
	--¾ÞÁ¦ÉñÔ³£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jlsy1=[[Audio/Sound/War/jlsy1.ogg]],
	jlsy2=[[Audio/Sound/Model/jlsy2.mp3]],
	jlsy3=[[Audio/Sound/Model/jlsy3.mp3]],
	jlsy4=[[Audio/Sound/Model/jlsy4.mp3]],
	jlsy5=[[Audio/Sound/Model/jlsy5.mp3]],
	--Ìì½«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	tj1=[[Audio/Sound/War/tj1.ogg]],
	tj2=[[Audio/Sound/Model/tj2.mp3]],
	tj3=[[Audio/Sound/Model/tj3.mp3]],
	tj4=[[Audio/Sound/Model/tj4.mp3]],
	tj5=[[Audio/Sound/Model/tj5.mp3]],
	--°Ù×ã½«¾ü£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	bzjj1=[[Audio/Sound/War/bzjj1.ogg]],
	bzjj2=[[Audio/Sound/Model/bzjj2.mp3]],
	bzjj3=[[Audio/Sound/Model/bzjj3.mp3]],
	bzjj4=[[Audio/Sound/Model/bzjj4.mp3]],
	bzjj5=[[Audio/Sound/Model/bzjj5.mp3]],
	--ÐÞÂÞ¿þÀÜÑý£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xlkly1=[[Audio/Sound/War/xlkly1.ogg]],
	xlkly2=[[Audio/Sound/Model/xlkly2.mp3]],
	xlkly3=[[Audio/Sound/Model/xlkly3.mp3]],
	xlkly4=[[Audio/Sound/Model/xlkly4.mp3]],
	xlkly5=[[Audio/Sound/Model/xlkly5.mp3]],
	--÷¼÷Ã¹Ö£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	klg1=[[Audio/Sound/War/klg1.ogg]],
	klg2=[[Audio/Sound/Model/klg2.mp3]],
	klg3=[[Audio/Sound/Model/klg3.mp3]],
	klg4=[[Audio/Sound/Model/klg4.mp3]],
	klg5=[[Audio/Sound/Model/klg5.mp3]],
	--µØÓüÕ½Éñ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	dyzs1=[[Audio/Sound/War/dyzs1.ogg]],
	dyzs2=[[Audio/Sound/Model/dyzs2.mp3]],
	dyzs3=[[Audio/Sound/Model/dyzs3.mp3]],
	dyzs4=[[Audio/Sound/Model/dyzs4.mp3]],
	dyzs5=[[Audio/Sound/Model/dyzs5.mp3]],
	--°×ÐÜ.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	bx1=[[Audio/Sound/War/bx1.ogg]],
	bx2=[[Audio/Sound/Model/bx2.mp3]],
	bx3=[[Audio/Sound/Model/bx3.mp3]],
	bx4=[[Audio/Sound/Model/bx4.mp3]],
	bx5=[[Audio/Sound/Model/bx5.mp3]],
	--Ü½ÈØÏÉ×Ó£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	frxz1=[[Audio/Sound/War/frxz1.ogg]],
	frxz2=[[Audio/Sound/Model/frxz2.mp3]],
	frxz3=[[Audio/Sound/Model/frxz3.mp3]],
	frxz4=[[Audio/Sound/Model/frxz4.mp3]],
	frxz5=[[Audio/Sound/Model/frxz5.mp3]],
	--ò×ÆøÑý£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	sqy1=[[Audio/Sound/War/sqy1.ogg]],
	sqy2=[[Audio/Sound/Model/sqy2.mp3]],
	sqy3=[[Audio/Sound/Model/sqy3.mp3]],
	sqy4=[[Audio/Sound/Model/sqy4.mp3]],
	sqy5=[[Audio/Sound/Model/sqy5.mp3]],
	--½ðÉíÂÞºº£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jslh1=[[Audio/Sound/War/jslh1.ogg]],
	jslh2=[[Audio/Sound/Model/jslh2.mp3]],
	jslh3=[[Audio/Sound/Model/jslh3.mp3]],
	jslh4=[[Audio/Sound/Model/jslh4.mp3]],
	jslh5=[[Audio/Sound/Model/jslh5.mp3]],
	--ÐÞÂÞ¿þÀÜ¹í£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xlklg1=[[Audio/Sound/War/xlklg1.ogg]],
	xlklg2=[[Audio/Sound/Model/xlklg2.mp3]],
	xlklg3=[[Audio/Sound/Model/xlklg3.mp3]],
	xlklg4=[[Audio/Sound/Model/xlklg4.mp3]],
	xlklg5=[[Audio/Sound/Model/xlklg5.mp3]],
	--òÔÁú£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jl1=[[Audio/Sound/War/jl1.ogg]],
	jl2=[[Audio/Sound/Model/jl2.mp3]],
	jl3=[[Audio/Sound/Model/jl3.mp3]],
	jl4=[[Audio/Sound/Model/jl4.mp3]],
	jl5=[[Audio/Sound/Model/jl5.mp3]],
	--Ñ²ÓÎÌìÉñ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xyts1=[[Audio/Sound/War/xyts1.ogg]],
	xyts2=[[Audio/Sound/Model/xyts2.mp3]],
	xyts3=[[Audio/Sound/Model/xyts3.mp3]],
	xyts4=[[Audio/Sound/Model/xyts4.mp3]],
	xyts5=[[Audio/Sound/Model/xyts5.mp3]],
	--ÌÙÂûÑý»¨£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	tmyh1=[[Audio/Sound/War/tmyh1.ogg]],
	tmyh2=[[Audio/Sound/Model/tmyh2.mp3]],
	tmyh3=[[Audio/Sound/Model/tmyh3.mp3]],
	tmyh4=[[Audio/Sound/Model/tmyh4.mp3]],
	tmyh5=[[Audio/Sound/Model/tmyh5.mp3]],
	--»¤ÎÀ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hw1=[[Audio/Sound/War/hw1.ogg]],
	hw2=[[Audio/Sound/Model/hw2.mp3]],
	hw3=[[Audio/Sound/Model/hw3.mp3]],
	hw4=[[Audio/Sound/Model/hw4.mp3]],
	hw5=[[Audio/Sound/Model/hw5.mp3]],
	--ÕÂÓã£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	zy1=[[Audio/Sound/War/zy1.ogg]],
	zy2=[[Audio/Sound/Model/zy2.mp3]],
	zy3=[[Audio/Sound/Model/zy3.mp3]],
	zy4=[[Audio/Sound/Model/zy4.mp3]],
	zy5=[[Audio/Sound/Model/zy5.mp3]],
	--´óòùòð£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	dbf1=[[Audio/Sound/War/dbf1.ogg]],
	dbf2=[[Audio/Sound/Model/dbf2.mp3]],
	dbf3=[[Audio/Sound/Model/dbf3.mp3]],
	dbf4=[[Audio/Sound/Model/dbf4.mp3]],
	dbf5=[[Audio/Sound/Model/dbf5.mp3]],
	--¶ÄÍ½£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	dt1=[[Audio/Sound/War/dt1.ogg]],
	dt2=[[Audio/Sound/Model/dt2.mp3]],
	dt3=[[Audio/Sound/Model/dt3.mp3]],
	dt4=[[Audio/Sound/Model/dt4.mp3]],
	dt5=[[Audio/Sound/Model/dt5.mp3]],
	--º£Ã«³æ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hmc1=[[Audio/Sound/War/hmc1.ogg]],
	hmc2=[[Audio/Sound/Model/hmc2.mp3]],
	hmc3=[[Audio/Sound/Model/hmc3.mp3]],
	hmc4=[[Audio/Sound/Model/hmc4.mp3]],
	hmc5=[[Audio/Sound/Model/hmc5.mp3]],
	--Ç¿µÁ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	qd1=[[Audio/Sound/War/qd1.ogg]],
	qd2=[[Audio/Sound/Model/qd2.mp3]],
	qd3=[[Audio/Sound/Model/qd3.mp3]],
	qd4=[[Audio/Sound/Model/qd4.mp3]],
	qd5=[[Audio/Sound/Model/qd5.mp3]],
	--É½Ôô£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	sz1=[[Audio/Sound/War/sz1.ogg]],
	sz2=[[Audio/Sound/Model/sz2.mp3]],
	sz3=[[Audio/Sound/Model/sz3.mp3]],
	sz4=[[Audio/Sound/Model/sz4.mp3]],
	sz5=[[Audio/Sound/Model/sz5.mp3]],
	--Ò°Öí£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	yz1=[[Audio/Sound/War/yz1.ogg]],
	yz2=[[Audio/Sound/Model/yz2.mp3]],
	yz3=[[Audio/Sound/Model/yz3.mp3]],
	yz4=[[Audio/Sound/Model/yz4.mp3]],
	yz5=[[Audio/Sound/Model/yz5.mp3]],
	--¸òó¡¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hmj1=[[Audio/Sound/War/hmj1.ogg]],
	hmj2=[[Audio/Sound/Model/hmj2.mp3]],
	hmj3=[[Audio/Sound/Model/hmj3.mp3]],
	hmj4=[[Audio/Sound/Model/hmj4.mp3]],
	hmj5=[[Audio/Sound/Model/hmj5.mp3]],
	--ºÚÐÜ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	zhx1=[[Audio/Sound/War/zhx1.ogg]],
	zhx2=[[Audio/Sound/Model/zhx2.mp3]],
	zhx3=[[Audio/Sound/Model/zhx3.mp3]],
	zhx4=[[Audio/Sound/Model/zhx4.mp3]],
	zhx5=[[Audio/Sound/Model/zhx5.mp3]],
	--ºüÀê¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hlj1=[[Audio/Sound/War/hlj1.ogg]],
	hlj2=[[Audio/Sound/Model/hlj2.mp3]],
	hlj3=[[Audio/Sound/Model/hlj3.mp3]],
	hlj4=[[Audio/Sound/Model/hlj4.mp3]],
	hlj5=[[Audio/Sound/Model/hlj5.mp3]],
	--»¨Ñý£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hy1=[[Audio/Sound/War/hy1.ogg]],
	hy2=[[Audio/Sound/Model/hy2.mp3]],
	hy3=[[Audio/Sound/Model/hy3.mp3]],
	hy4=[[Audio/Sound/Model/hy4.mp3]],
	hy5=[[Audio/Sound/Model/hy5.mp3]],
	--ÀÏ»¢£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	lh1=[[Audio/Sound/War/lh1.ogg]],
	lh2=[[Audio/Sound/Model/lh2.mp3]],
	lh3=[[Audio/Sound/Model/lh3.mp3]],
	lh4=[[Audio/Sound/Model/lh4.mp3]],
	lh5=[[Audio/Sound/Model/lh5.mp3]],
	--ÑòÍ·¹Ö£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	ytg1=[[Audio/Sound/War/ytg1.ogg]],
	ytg2=[[Audio/Sound/Model/ytg2.mp3]],
	ytg3=[[Audio/Sound/Model/ytg3.mp3]],
	ytg4=[[Audio/Sound/Model/ytg4.mp3]],
	ytg5=[[Audio/Sound/Model/ytg5.mp3]],
	--Å£Ñý£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	ny1=[[Audio/Sound/War/ny1.ogg]],
	ny2=[[Audio/Sound/Model/ny2.mp3]],
	ny3=[[Audio/Sound/Model/ny3.mp3]],
	ny4=[[Audio/Sound/Model/ny4.mp3]],
	ny5=[[Audio/Sound/Model/ny5.mp3]],
	--Ïº±ø£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xb1=[[Audio/Sound/War/xb1.ogg]],
	xb2=[[Audio/Sound/Model/xb2.mp3]],
	xb3=[[Audio/Sound/Model/xb3.mp3]],
	xb4=[[Audio/Sound/Model/xb4.mp3]],
	xb5=[[Audio/Sound/Model/xb5.mp3]],
	--Ð¡ÁúÅ®£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xln1=[[Audio/Sound/War/xln1.ogg]],
	xln2=[[Audio/Sound/Model/xln2.mp3]],
	xln3=[[Audio/Sound/Model/xln3.mp3]],
	xln4=[[Audio/Sound/Model/xln4.mp3]],
	xln5=[[Audio/Sound/Model/xln5.mp3]],
	--Ð·½«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xj1=[[Audio/Sound/War/xj1.ogg]],
	xj2=[[Audio/Sound/Model/xj2.mp3]],
	xj3=[[Audio/Sound/Model/xj3.mp3]],
	xj4=[[Audio/Sound/Model/xj4.mp3]],
	xj5=[[Audio/Sound/Model/xj5.mp3]],
	--¹êØ©Ïà£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	gcx1=[[Audio/Sound/War/gcx1.ogg]],
	gcx2=[[Audio/Sound/Model/gcx2.mp3]],
	gcx3=[[Audio/Sound/Model/gcx3.mp3]],
	gcx4=[[Audio/Sound/Model/gcx4.mp3]],
	gcx5=[[Audio/Sound/Model/gcx5.mp3]],
	--ºÚÐÜ¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hxj1=[[Audio/Sound/War/hxj1.ogg]],
	hxj2=[[Audio/Sound/Model/hxj2.mp3]],
	hxj3=[[Audio/Sound/Model/hxj3.mp3]],
	hxj4=[[Audio/Sound/Model/hxj4.mp3]],
	hxj5=[[Audio/Sound/Model/hxj5.mp3]],
	--½©Ê¬£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	js1=[[Audio/Sound/War/js1.ogg]],
	js2=[[Audio/Sound/Model/js2.mp3]],
	js3=[[Audio/Sound/Model/js3.mp3]],
	js4=[[Audio/Sound/Model/js4.mp3]],
	js5=[[Audio/Sound/Model/js5.mp3]],
	--ÍÃ×Ó¹Ö£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	tzg1=[[Audio/Sound/War/tzg1.ogg]],
	tzg2=[[Audio/Sound/Model/tzg2.mp3]],
	tzg3=[[Audio/Sound/Model/tzg3.mp3]],
	tzg4=[[Audio/Sound/Model/tzg4.mp3]],
	tzg5=[[Audio/Sound/Model/tzg5.mp3]],
	--Ö©Öë¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	zzj1=[[Audio/Sound/War/zzj1.ogg]],
	zzj2=[[Audio/Sound/Model/zzj2.mp3]],
	zzj3=[[Audio/Sound/Model/zzj3.mp3]],
	zzj4=[[Audio/Sound/Model/zzj4.mp3]],
	zzj5=[[Audio/Sound/Model/zzj5.mp3]],
	--ºÚÉ½ÀÏÑý£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hsly1=[[Audio/Sound/War/hsly1.ogg]],
	hsly2=[[Audio/Sound/Model/hsly2.mp3]],
	hsly3=[[Audio/Sound/Model/hsly3.mp3]],
	hsly4=[[Audio/Sound/Model/hsly4.mp3]],
	hsly5=[[Audio/Sound/Model/hsly5.mp3]],
	--ºûµûÏÉ×Ó£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hdxz1=[[Audio/Sound/War/hdxz1.ogg]],
	hdxz2=[[Audio/Sound/Model/hdxz2.mp3]],
	hdxz3=[[Audio/Sound/Model/hdxz3.mp3]],
	hdxz4=[[Audio/Sound/Model/hdxz4.mp3]],
	hdxz5=[[Audio/Sound/Model/hdxz5.mp3]],
	--·ç²®£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	fb1=[[Audio/Sound/War/fb1.ogg]],
	fb2=[[Audio/Sound/Model/fb2.mp3]],
	fb3=[[Audio/Sound/Model/fb3.mp3]],
	fb4=[[Audio/Sound/Model/fb4.mp3]],
	fb5=[[Audio/Sound/Model/fb5.mp3]],
	--°ö¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	bj1=[[Audio/Sound/War/bj1.ogg]],
	bj2=[[Audio/Sound/Model/bj2.mp3]],
	bj3=[[Audio/Sound/Model/bj3.mp3]],
	bj4=[[Audio/Sound/Model/bj4.mp3]],
	bj5=[[Audio/Sound/Model/bj5.mp3]],
	--±ÌË®Ò¹²æ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	bsyc1=[[Audio/Sound/War/bsyc1.ogg]],
	bsyc2=[[Audio/Sound/Model/bsyc2.mp3]],
	bsyc3=[[Audio/Sound/Model/bsyc3.mp3]],
	bsyc4=[[Audio/Sound/Model/bsyc4.mp3]],
	bsyc5=[[Audio/Sound/Model/bsyc5.mp3]],
	--öÞÈË£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jr1=[[Audio/Sound/War/jr1.ogg]],
	jr2=[[Audio/Sound/Model/jr2.mp3]],
	jr3=[[Audio/Sound/Model/jr3.mp3]],
	jr4=[[Audio/Sound/Model/jr4.mp3]],
	jr5=[[Audio/Sound/Model/jr5.mp3]],
	--ÓêÊ¦£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	ys1=[[Audio/Sound/War/ys1.ogg]],
	ys2=[[Audio/Sound/Model/ys2.mp3]],
	ys3=[[Audio/Sound/Model/ys3.mp3]],
	ys4=[[Audio/Sound/Model/ys4.mp3]],
	ys5=[[Audio/Sound/Model/ys5.mp3]],
	--½õÃ«õõ¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jmdj1=[[Audio/Sound/War/jmdj1.ogg]],
	jmdj2=[[Audio/Sound/Model/jmdj2.mp3]],
	jmdj3=[[Audio/Sound/Model/jmdj3.mp3]],
	jmdj4=[[Audio/Sound/Model/jmdj4.mp3]],
	jmdj5=[[Audio/Sound/Model/jmdj5.mp3]],
	--Ç§ÄêÉß÷È£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	qnsm1=[[Audio/Sound/War/qnsm1.ogg]],
	qnsm2=[[Audio/Sound/Model/qnsm2.mp3]],
	qnsm3=[[Audio/Sound/Model/qnsm3.mp3]],
	qnsm4=[[Audio/Sound/Model/qnsm4.mp3]],
	qnsm5=[[Audio/Sound/Model/qnsm5.mp3]],
	--ÈçÒâÏÉ×Ó£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	ryxz1=[[Audio/Sound/War/ryxz1.ogg]],
	ryxz2=[[Audio/Sound/Model/ryxz2.mp3]],
	ryxz3=[[Audio/Sound/Model/ryxz3.mp3]],
	ryxz4=[[Audio/Sound/Model/ryxz4.mp3]],
	ryxz5=[[Audio/Sound/Model/ryxz5.mp3]],
	--Ï¬Å£½«¾üÈËÐÎ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xnjjr1=[[Audio/Sound/War/xnjjr1.ogg]],
	xnjjr2=[[Audio/Sound/Model/xnjjr2.mp3]],
	xnjjr3=[[Audio/Sound/Model/xnjjr3.mp3]],
	xnjjr4=[[Audio/Sound/Model/xnjjr4.mp3]],
	xnjjr5=[[Audio/Sound/Model/xnjjr5.mp3]],
	--Ï¬Å£½«¾üÊÞÐÍ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xnjjs1=[[Audio/Sound/War/xnjjs1.ogg]],
	xnjjs2=[[Audio/Sound/Model/xnjjs2.mp3]],
	xnjjs3=[[Audio/Sound/Model/xnjjs3.mp3]],
	xnjjs4=[[Audio/Sound/Model/xnjjs4.mp3]],
	xnjjs5=[[Audio/Sound/Model/xnjjs5.mp3]],
	--ÊóÏÈ·æ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	sxf1=[[Audio/Sound/War/sxf1.ogg]],
	sxf2=[[Audio/Sound/Model/sxf2.mp3]],
	sxf3=[[Audio/Sound/Model/sxf3.mp3]],
	sxf4=[[Audio/Sound/Model/sxf4.mp3]],
	sxf5=[[Audio/Sound/Model/sxf5.mp3]],
	--Ò°Öí¾«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	yzj1=[[Audio/Sound/War/yzj1.ogg]],
	yzj2=[[Audio/Sound/Model/yzj2.mp3]],
	yzj3=[[Audio/Sound/Model/yzj3.mp3]],
	yzj4=[[Audio/Sound/Model/yzj4.mp3]],
	yzj5=[[Audio/Sound/Model/yzj5.mp3]],
	--Áé·ûÅ®æ´£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	lfnw1=[[Audio/Sound/War/lfnw1.ogg]],
	lfnw2=[[Audio/Sound/Model/lfnw2.mp3]],
	lfnw3=[[Audio/Sound/Model/lfnw3.mp3]],
	lfnw4=[[Audio/Sound/Model/lfnw4.mp3]],
	--ÂÉ·¨Å®æ´£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	alfnw1=[[Audio/Sound/War/alfnw1.ogg]],
	alfnw2=[[Audio/Sound/Model/alfnw2.mp3]],
	alfnw3=[[Audio/Sound/Model/alfnw3.mp3]],
	alfnw4=[[Audio/Sound/Model/alfnw4.mp3]],
	alfnw5=[[Audio/Sound/Model/alfnw5.mp3]],
	--ÎüÑª¹í£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	xxg1=[[Audio/Sound/War/xxg1.ogg]],
	xxg2=[[Audio/Sound/Model/xxg2.mp3]],
	xxg3=[[Audio/Sound/Model/xxg3.mp3]],
	xxg4=[[Audio/Sound/Model/xxg4.mp3]],
	xxg5=[[Audio/Sound/Model/xxg5.mp3]],
	--ÒõÑôÉ¡£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	yys1=[[Audio/Sound/War/yys1.ogg]],
	yys2=[[Audio/Sound/Model/yys2.mp3]],
	yys3=[[Audio/Sound/Model/yys3.mp3]],
	yys4=[[Audio/Sound/Model/yys4.mp3]],
	yys5=[[Audio/Sound/Model/yys5.mp3]],
	--ÓÄÁé£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	yl1=[[Audio/Sound/War/yl1.ogg]],
	yl2=[[Audio/Sound/Model/yl2.mp3]],
	yl3=[[Audio/Sound/Model/yl3.mp3]],
	yl4=[[Audio/Sound/Model/yl4.mp3]],
	yl5=[[Audio/Sound/Model/yl5.mp3]],
	--¹í½«£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	gj1=[[Audio/Sound/War/gj1.ogg]],
	gj2=[[Audio/Sound/Model/gj2.mp3]],
	gj3=[[Audio/Sound/Model/gj3.mp3]],
	gj4=[[Audio/Sound/Model/gj4.mp3]],
	gj5=[[Audio/Sound/Model/gj5.mp3]],
	--»­»ê£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hh1=[[Audio/Sound/War/hh1.ogg]],
	hh2=[[Audio/Sound/Model/hh2.mp3]],
	hh3=[[Audio/Sound/Model/hh3.mp3]],
	hh4=[[Audio/Sound/Model/hh4.mp3]],
	hh5=[[Audio/Sound/Model/hh5.mp3]],
	--¾»Æ¿Å®æ´£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jpnw1=[[Audio/Sound/War/jpnw1.ogg]],
	jpnw2=[[Audio/Sound/Model/jpnw2.mp3]],
	jpnw3=[[Audio/Sound/Model/jpnw3.mp3]],
	jpnw4=[[Audio/Sound/Model/jpnw4.mp3]],
	jpnw5=[[Audio/Sound/Model/jpnw5.mp3]],
	--ÓÄÚ¤ÍÞÍÞ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	ymww1=[[Audio/Sound/War/ymww1.ogg]],
	ymww2=[[Audio/Sound/Model/ymww2.mp3]],
	ymww3=[[Audio/Sound/Model/ymww3.mp3]],
	ymww4=[[Audio/Sound/Model/ymww4.mp3]],
	ymww5=[[Audio/Sound/Model/ymww5.mp3]],
	--´óÁ¦½ð¸Õ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	dljg1=[[Audio/Sound/War/dljg1.ogg]],
	dljg2=[[Audio/Sound/Model/dljg2.mp3]],
	dljg3=[[Audio/Sound/Model/dljg3.mp3]],
	dljg4=[[Audio/Sound/Model/dljg4.mp3]],
	dljg5=[[Audio/Sound/Model/dljg5.mp3]],
	--Áéº×£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	lha1=[[Audio/Sound/War/lha1.ogg]],
	lha2=[[Audio/Sound/Model/lha2.mp3]],
	lha3=[[Audio/Sound/Model/lha3.mp3]],
	lha4=[[Audio/Sound/Model/lha4.mp3]],
	lha5=[[Audio/Sound/Model/lha5.mp3]],
	--ÊÉÌì»¢£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	sth1=[[Audio/Sound/War/sth1.ogg]],
	sth2=[[Audio/Sound/Model/sth2.mp3]],
	sth3=[[Audio/Sound/Model/sth3.mp3]],
	sth4=[[Audio/Sound/Model/sth4.mp3]],
	sth5=[[Audio/Sound/Model/sth5.mp3]],
	--ÎíÖÐÏÉ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	wzx1=[[Audio/Sound/War/wzx1.ogg]],
	wzx2=[[Audio/Sound/Model/wzx2.mp3]],
	wzx3=[[Audio/Sound/Model/wzx3.mp3]],
	wzx4=[[Audio/Sound/Model/wzx4.mp3]],
	wzx5=[[Audio/Sound/Model/wzx5.mp3]],
	--Ñ×Ä§Éñ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	yms1=[[Audio/Sound/War/yms1.ogg]],
	yms2=[[Audio/Sound/Model/yms2.mp3]],
	yms3=[[Audio/Sound/Model/yms3.mp3]],
	yms4=[[Audio/Sound/Model/yms4.mp3]],
	yms5=[[Audio/Sound/Model/yms5.mp3]],
	--Ò¹ÂÞÉ²£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	ylc1=[[Audio/Sound/War/ylc1.ogg]],
	ylc2=[[Audio/Sound/Model/ylc2.mp3]],
	ylc3=[[Audio/Sound/Model/ylc3.mp3]],
	ylc4=[[Audio/Sound/Model/ylc4.mp3]],
	ylc5=[[Audio/Sound/Model/ylc5.mp3]],
	--ºìÝàÏÉ×Ó£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	hexz1=[[Audio/Sound/War/hexz1.ogg]],
	hexz2=[[Audio/Sound/Model/hexz2.mp3]],
	hexz3=[[Audio/Sound/Model/hexz3.mp3]],
	hexz4=[[Audio/Sound/Model/hexz4.mp3]],
	hexz5=[[Audio/Sound/Model/hexz5.mp3]],
	--»ú¹ØÈË£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jgr1=[[Audio/Sound/War/jgr1.ogg]],
	jgr2=[[Audio/Sound/Model/jgr2.mp3]],
	jgr3=[[Audio/Sound/Model/jgr3.mp3]],
	jgr4=[[Audio/Sound/Model/jgr4.mp3]],
	jgr5=[[Audio/Sound/Model/jgr5.mp3]],
	--Áú¹ê£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	lg1=[[Audio/Sound/War/lg1.ogg]],
	lg2=[[Audio/Sound/Model/lg2.mp3]],
	lg3=[[Audio/Sound/Model/lg3.mp3]],
	lg4=[[Audio/Sound/Model/lg4.mp3]],
	lg5=[[Audio/Sound/Model/lg5.mp3]],
	--Ì¤ÔÆÊÞ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	tys1=[[Audio/Sound/War/tys1.ogg]],
	tys2=[[Audio/Sound/Model/tys2.mp3]],
	tys3=[[Audio/Sound/Model/tys3.mp3]],
	tys4=[[Audio/Sound/Model/tys4.mp3]],
	tys5=[[Audio/Sound/Model/tys5.mp3]],
	--°ÍÉß£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	bs1=[[Audio/Sound/War/bs1.ogg]],
	bs2=[[Audio/Sound/Model/bs2.mp3]],
	bs3=[[Audio/Sound/Model/bs3.mp3]],
	bs4=[[Audio/Sound/Model/bs4.mp3]],
	bs5=[[Audio/Sound/Model/bs5.mp3]],
	--»ú¹ØÄñ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jgn1=[[Audio/Sound/War/jgn1.ogg]],
	jgn2=[[Audio/Sound/Model/jgn2.mp3]],
	jgn3=[[Audio/Sound/Model/jgn3.mp3]],
	jgn4=[[Audio/Sound/Model/jgn4.mp3]],
	jgn5=[[Audio/Sound/Model/jgn5.mp3]],
	--»ú¹ØÊÞ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	jgs1=[[Audio/Sound/War/jgs1.ogg]],
	jgs2=[[Audio/Sound/Model/jgs2.mp3]],
	jgs3=[[Audio/Sound/Model/jgs3.mp3]],
	jgs4=[[Audio/Sound/Model/jgs4.mp3]],
	jgs5=[[Audio/Sound/Model/jgs5.mp3]],
	--¿ñ±ªÊÞÐÍ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	kbs1=[[Audio/Sound/War/kbs1.ogg]],
	kbs2=[[Audio/Sound/Model/kbs2.mp3]],
	kbs3=[[Audio/Sound/Model/kbs3.mp3]],
	kbs4=[[Audio/Sound/Model/kbs4.mp3]],
	kbs5=[[Audio/Sound/Model/kbs5.mp3]],
	--Á¬åó³µ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	lnc1=[[Audio/Sound/War/lnc1.ogg]],
	lnc2=[[Audio/Sound/Model/lnc2.mp3]],
	lnc3=[[Audio/Sound/Model/lnc3.mp3]],
	lnc4=[[Audio/Sound/Model/lnc4.mp3]],
	lnc5=[[Audio/Sound/Model/lnc5.mp3]],
	--Ã¨ÁéÊÞÐÍ£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	mlsx1=[[Audio/Sound/War/mlsx1.ogg]],
	mlsx2=[[Audio/Sound/Model/mlsx2.mp3]],
	mlsx3=[[Audio/Sound/Model/mlsx3.mp3]],
	mlsx4=[[Audio/Sound/Model/mlsx4.mp3]],
	mlsx5=[[Audio/Sound/Model/mlsx5.mp3]],
	--Ê÷¹Ö£º1.¹¥»÷      2.Ê©·¨    3.°¤´ò        4.·ÀÓù      5.µ¹µØ
	sg1=[[Audio/Sound/War/sg1.ogg]],
	sg2=[[Audio/Sound/Model/sg2.mp3]],
	sg3=[[Audio/Sound/Model/sg3.mp3]],
	sg4=[[Audio/Sound/Model/sg4.mp3]],
	sg5=[[Audio/Sound/Model/sg5.mp3]],
----------------------------------------------------

	baohu=[[Audio/Sound/War/baohu.ogg]],
	baoyu=[[Audio/Sound/War/baoyu.ogg]],
	baozha=[[Audio/Sound/War/baozha.ogg]],
	bdmw=[[Audio/Sound/War/bdmw.ogg]],
	bfwl=[[Audio/Sound/War/bfwl.ogg]],
	bingsui=[[Audio/Sound/War/bingsui.ogg]],
	bk1=[[Audio/Sound/Model/bk1.mp3]],
	bs1=[[Audio/Sound/Model/bs1.mp3]],
	bsz1=[[Audio/Sound/Model/bsz1.mp3]],
	bsz2=[[Audio/Sound/Model/bsz2.mp3]],
	bsz3=[[Audio/Sound/Model/bsz3.mp3]],
	bt1=[[Audio/Sound/Model/bt1.mp3]],
	cf1=[[Audio/Sound/Model/cf1.mp3]],
	cxds=[[Audio/Sound/War/cxds.ogg]],
	cxds1=[[Audio/Sound/War/cxds1.ogg]],
	cxds2=[[Audio/Sound/War/cxds2.ogg]],
	dao=[[Audio/Sound/War/dao.ogg]],
	dhty1=[[Audio/Sound/Model/dhty1.mp3]],
	dhty2=[[Audio/Sound/Model/dhty2.mp3]],
	dhty3=[[Audio/Sound/Model/dhty3.mp3]],
	dianliu=[[Audio/Sound/War/dianliu.ogg]],
	dilie=[[Audio/Sound/War/dilie.ogg]],
	dj1=[[Audio/Sound/Model/dj1.mp3]],
	dj2=[[Audio/Sound/Model/dj2.mp3]],
	dj3=[[Audio/Sound/Model/dj3.mp3]],
	dz1=[[Audio/Sound/Model/dz1.mp3]],
	fangyu=[[Audio/Sound/War/fangyu.ogg]],
	fbjy=[[Audio/Sound/Model/fbjy.mp3]],
	fbjy1=[[Audio/Sound/Model/fbjy1.mp3]],
	feng=[[Audio/Sound/War/feng.ogg]],
	ffwb=[[Audio/Sound/War/ffwb.ogg]],
	fh1=[[Audio/Sound/Model/fh1.mp3]],
	fh2=[[Audio/Sound/Model/fh2.mp3]],
	fh3=[[Audio/Sound/Model/fh3.mp3]],
	fjcy=[[Audio/Sound/War/fjcy.ogg]],
	flbf=[[Audio/Sound/War/flbf.ogg]],
	flz=[[Audio/Sound/War/flz.ogg]],
	foyin=[[Audio/Sound/War/foyin.ogg]],
	fqr1=[[Audio/Sound/Model/fqr1.mp3]],
	fqr2=[[Audio/Sound/Model/fqr2.mp3]],
	fqr3=[[Audio/Sound/Model/fqr3.mp3]],
	fqz1=[[Audio/Sound/Model/fqz1.mp3]],
	fqz2=[[Audio/Sound/Model/fqz2.mp3]],
	fs1=[[Audio/Sound/Model/fs1.mp3]],
	ftnh=[[Audio/Sound/War/ftnh.ogg]],
	fuhuo=[[Audio/Sound/War/fuhuo.ogg]],
	fyld=[[Audio/Sound/War/fyld.ogg]],
	fz1=[[Audio/Sound/Model/fz1.mp3]],
	gong=[[Audio/Sound/War/gong.ogg]],
	gou1=[[Audio/Sound/War/gou1.ogg]],
	gou2=[[Audio/Sound/War/gou2.ogg]],
	gunbang=[[Audio/Sound/War/gunbang.ogg]],
	hd1=[[Audio/Sound/Model/hd1.mp3]],
	hdjy1=[[Audio/Sound/Model/hdjy1.mp3]],
	he1=[[Audio/Sound/War/he1.ogg]],
	he2=[[Audio/Sound/War/he2.ogg]],
	hk1=[[Audio/Sound/Model/hk1.mp3]],
	hn1=[[Audio/Sound/Model/hn1.mp3]],
	huifu=[[Audio/Sound/War/huifu.ogg]],
	hy1=[[Audio/Sound/Model/hy1.mp3]],
    hy2=[[Audio/Sound/Model/hy2.mp3]],
	hy3=[[Audio/Sound/Model/hy3.mp3]],
	jdwg=[[Audio/Sound/War/jdwg.ogg]],
	jhjz=[[Audio/Sound/War/jhjz.ogg]],
	jhjz1=[[Audio/Sound/War/jhjz1.ogg]],
	jhjz2=[[Audio/Sound/War/jhjz2.ogg]],
	jiafang=[[Audio/Sound/War/jiafang.ogg]],
	jian=[[Audio/Sound/War/jian.ogg]],
	jiguan1=[[Audio/Sound/War/jiguan1.ogg]],
	jiguan2=[[Audio/Sound/War/jiguan2.ogg]],
	jlq=[[Audio/Sound/War/jlq.ogg]],
	jplt=[[Audio/Sound/War/jplt.ogg]],
	jqss=[[Audio/Sound/War/jqss.ogg]],
	jrsz1=[[Audio/Sound/Model/jrsz1.mp3]],
	jtbf=[[Audio/Sound/War/jtbf.ogg]],
	jtbf1=[[Audio/Sound/War/jtbf1.ogg]],
	jtbf2=[[Audio/Sound/War/jtbf2.ogg]],
	jtxn1=[[Audio/Sound/Model/jtxn1.mp3]],
	jtxn2=[[Audio/Sound/Model/jtxn2.mp3]],
	jtxn3=[[Audio/Sound/Model/jtxn3.mp3]],
	kjj1=[[Audio/Sound/War/kjj1.ogg]],
	kjj2=[[Audio/Sound/War/kjj2.ogg]],
	kjj3=[[Audio/Sound/War/kjj3.ogg]],
	langtao=[[Audio/Sound/War/langtao.ogg]],
	laohu1=[[Audio/Sound/War/laohu1.ogg]],
	laohu2=[[Audio/Sound/War/laohu2.ogg]],
	laoren1=[[Audio/Sound/Model/laoren1.mp3]],
	leiming=[[Audio/Sound/War/leiming.ogg]],
	lh=[[Audio/Sound/War/lh.ogg]],
	ljgz1=[[Audio/Sound/Model/ljgz1.mp3]],
	ljgz2=[[Audio/Sound/Model/ljgz2.mp3]],
	ljgz3=[[Audio/Sound/Model/ljgz3.mp3]],
	long1=[[Audio/Sound/War/long1.ogg]],
	long2=[[Audio/Sound/War/long2.ogg]],
	lr1=[[Audio/Sound/Model/lr1.mp3]],
	lstx=[[Audio/Sound/War/lstx.ogg]],
	mh=[[Audio/Sound/War/mh.ogg]],
	mh1=[[Audio/Sound/War/mh1.ogg]],
	mh2=[[Audio/Sound/War/mh2.ogg]],
	mls=[[Audio/Sound/War/mls.ogg]],
	mn1=[[Audio/Sound/Model/mn1.mp3]],
	mr1=[[Audio/Sound/Model/mr1.mp3]],
	mr2=[[Audio/Sound/Model/mr2.mp3]],
	mr3=[[Audio/Sound/Model/mr3.mp3]],
	nanzi1=[[Audio/Sound/Model/nanzi1.mp3]],
	nanzi2=[[Audio/Sound/Model/nanzi2.mp3]],
	nvzi1=[[Audio/Sound/Model/nvzi1.mp3]],
	nvzi2=[[Audio/Sound/Model/nvzi2.mp3]],
	penhuo=[[Audio/Sound/War/penhuo.ogg]],
	pfcz=[[Audio/Sound/War/pfcz.ogg]],
	piaodai=[[Audio/Sound/War/piaodai.ogg]],
	pzcj=[[Audio/Sound/War/pzcj.ogg]],
	qingxin=[[Audio/Sound/War/qingxin.ogg]],
	qr1=[[Audio/Sound/Model/qr1.mp3]],
	qr2=[[Audio/Sound/Model/qr2.mp3]],
	qr3=[[Audio/Sound/Model/qr3.mp3]],
	quanji=[[Audio/Sound/War/quanji.ogg]],
	qx=[[Audio/Sound/War/qx.ogg]],
	qx1=[[Audio/Sound/War/qx1.ogg]],
	qx2=[[Audio/Sound/War/qx2.ogg]],
	ranshao=[[Audio/Sound/War/ranshao.ogg]],
	sbdl=[[Audio/Sound/War/sbdl.ogg]],
	sbtj=[[Audio/Sound/War/sbtj.ogg]],
	shan=[[Audio/Sound/War/shan.ogg]],
	shaonian1=[[Audio/Sound/Model/shaonian1.mp3]],
	shaonian2=[[Audio/Sound/Model/shaonian2.mp3]],
	shaonv1=[[Audio/Sound/Model/shaonv1.mp3]],
	shaonv2=[[Audio/Sound/Model/shaonv2.mp3]],
	shuizhu=[[Audio/Sound/War/shuizhu.ogg]],
	sl=[[Audio/Sound/War/sl.ogg]],
	smds1=[[Audio/Sound/Model/smds1.mp3]],
	spl=[[Audio/Sound/War/spl.ogg]],
	ss1=[[Audio/Sound/Model/ss1.mp3]],
	syfs=[[Audio/Sound/War/syfs.ogg]],
	sz=[[Audio/Sound/War/sz.ogg]],
	taopao=[[Audio/Sound/War/taopao.ogg]],
	tb1=[[Audio/Sound/Model/tb1.mp3]],
	tj1=[[Audio/Sound/Model/tj1.mp3]],
	tmz1=[[Audio/Sound/Model/tmz1.mp3]],
	tyzr1=[[Audio/Sound/Model/tyzr1.mp3]],
	wfcb=[[Audio/Sound/War/wfcb.ogg]],
	wg1=[[Audio/Sound/Model/wg1.mp3]],
	wjgy1=[[Audio/Sound/War/wjgy1.ogg]],
	wjgy2=[[Audio/Sound/War/wjgy2.ogg]],
	wjgy3=[[Audio/Sound/War/wjgy3.ogg]],
	wjgy4=[[Audio/Sound/War/wjgy4.ogg]],
	wwdz=[[Audio/Sound/War/wwdz.ogg]],
	wwdz1=[[Audio/Sound/War/wwdz1.ogg]],
	wwdz2=[[Audio/Sound/War/wwdz2.ogg]],
	wwdz3=[[Audio/Sound/War/wwdz3.ogg]],
	wyy1=[[Audio/Sound/Model/wyy1.mp3]],
	wyy2=[[Audio/Sound/Model/wyy2.mp3]],
	wyy3=[[Audio/Sound/Model/wyy3.mp3]],
	["wyy3-1"]=[[Audio/Sound/Model/wyy3-1.mp3]],
	xe1=[[Audio/Sound/Model/xe1.mp3]],
	xhq=[[Audio/Sound/War/xhq.ogg]],
	xhs1=[[Audio/Sound/Model/xhs1.mp3]],
	xjs1=[[Audio/Sound/Model/xjs1.mp3]],
	["xjs1-1"]=[[Audio/Sound/Model/xjs1-1.mp3]],
	xlj=[[Audio/Sound/War/xlj.ogg]],
	xnh1=[[Audio/Sound/Model/xnh1.mp3]],
	xq1=[[Audio/Sound/Model/xq1.mp3]],
	xq2=[[Audio/Sound/Model/xq2.mp3]],
	xq3=[[Audio/Sound/Model/xq3.mp3]],
	xqgd=[[Audio/Sound/War/xqgd.ogg]],
	xssp=[[Audio/Sound/War/xssp.ogg]],
	xsydy1=[[Audio/Sound/Model/xsydy1.mp3]],
	xsydy10=[[Audio/Sound/Model/xsydy10.mp3]],
	xsydy11=[[Audio/Sound/Model/xsydy11.mp3]],
	xsydy12=[[Audio/Sound/Model/xsydy12.mp3]],
	xsydy13=[[Audio/Sound/Model/xsydy13.mp3]],
	xsydy14=[[Audio/Sound/Model/xsydy14.mp3]],
	xsydy15=[[Audio/Sound/Model/xsydy15.mp3]],
	xsydy16=[[Audio/Sound/Model/xsydy16.mp3]],
	xsydy17=[[Audio/Sound/Model/xsydy17.mp3]],
	xsydy18=[[Audio/Sound/Model/xsydy18.mp3]],
	xsydy19=[[Audio/Sound/Model/xsydy19.mp3]],
	xsydy2=[[Audio/Sound/Model/xsydy2.mp3]],
	xsydy20=[[Audio/Sound/Model/xsydy20.mp3]],
	xsydy3=[[Audio/Sound/Model/xsydy3.mp3]],
	xsydy4=[[Audio/Sound/Model/xsydy4.mp3]],
	xsydy5=[[Audio/Sound/Model/xsydy5.mp3]],
	xsydy6=[[Audio/Sound/Model/xsydy6.mp3]],
	xsydy7=[[Audio/Sound/Model/xsydy7.mp3]],
	xsydy8=[[Audio/Sound/Model/xsydy8.mp3]],
	xsydy9=[[Audio/Sound/Model/xsydy9.mp3]],
	xuli=[[Audio/Sound/War/xuli.ogg]],
	xx1=[[Audio/Sound/Model/xx1.mp3]],
	xx2=[[Audio/Sound/Model/xx2.mp3]],
	xx3=[[Audio/Sound/Model/xx3.mp3]],
	xy1=[[Audio/Sound/Model/xy1.mp3]],
	xy2=[[Audio/Sound/Model/xy2.mp3]],
	xy3=[[Audio/Sound/Model/xy3.mp3]],
	xycf=[[Audio/Sound/War/xycf.ogg]],
	ycx1=[[Audio/Sound/Model/ycx1.mp3]],
	ycx2=[[Audio/Sound/Model/ycx2.mp3]],
	ycx3=[[Audio/Sound/Model/ycx3.mp3]],
	yd=[[Audio/Sound/War/yd.ogg]],
	yeshou=[[Audio/Sound/War/yeshou.ogg]],
	yll=[[Audio/Sound/War/yll.ogg]],
	yqgy=[[Audio/Sound/War/yqgy.ogg]],
	ysj=[[Audio/Sound/War/ysj.ogg]],
	ysj1=[[Audio/Sound/War/ysj1.ogg]],
	ysj2=[[Audio/Sound/War/ysj2.ogg]],
	ytw1=[[Audio/Sound/Model/ytw1.mp3]],
	yunshi=[[Audio/Sound/War/yunshi.ogg]],
	yxj1=[[Audio/Sound/Model/yxj1.mp3]],
	yxj2=[[Audio/Sound/Model/yxj2.mp3]],
	yxj3=[[Audio/Sound/Model/yxj3.mp3]],
	yyy1=[[Audio/Sound/Model/yyy1.mp3]],
	yyy2=[[Audio/Sound/Model/yyy2.mp3]],
	yyy3=[[Audio/Sound/Model/yyy3.mp3]],
	zhanshen=[[Audio/Sound/War/zhanshen.ogg]],
	zhaohuan=[[Audio/Sound/War/zhaohuan.ogg]],
	zhujian=[[Audio/Sound/War/zhujian.ogg]],
	zj1=[[Audio/Sound/Model/zj1.mp3]],
	zj2=[[Audio/Sound/Model/zj2.mp3]],
	zj3=[[Audio/Sound/Model/zj3.mp3]],
	zk1=[[Audio/Sound/Model/zk1.mp3]],
	znfn1=[[Audio/Sound/Model/znfn1.mp3]],
	zs=[[Audio/Sound/War/zs.ogg]],
}
